# Generated by Django 5.2 on 2025-04-18 20:24

import custom_sessions.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=custom_sessions.models.assignment_submission_path)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('feedback_provided', models.BooleanField(default=False)),
                ('graded', models.BooleanField(default=False)),
                ('feedback_provided_at', models.DateTimeField(blank=True, null=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_assignmentsubmissions', to='dashboard.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_assignmentsubmissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('session_type', models.CharField(choices=[('on_campus', 'On-Campus'), ('off_campus', 'Off-Campus')], max_length=15)),
                ('classroom', models.CharField(blank=True, max_length=50, null=True)),
                ('location_link', models.URLField(blank=True, help_text='Paste Google Maps location if off-campus.')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_approved', models.BooleanField(default=False)),
                ('is_canceled', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_custom_sessions', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_custom_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
